var Categories = {
	'Architecture' : 'Cities',
	'Cities' : 'Cities',
	'Domed Cities' : 'Cities',
	'Business' : 'Commerce',
	'Credit Cards' : 'Commerce',
	'Shopping' : 'Commerce',
	'Computers' : 'Computers',
	'Tablet' : 'Computers',
	'Disneyland TV' : 'Disney',
	'EPCOT' : 'Disney',
	'Tomorrow Land' : 'Disney',
	'Alternative Energy' : 'Energy',
	'Nuclear Power' : 'Energy',
	'Solar Power' : 'Energy',
	'Fashion' : 'Fashion',
	'Farms' : 'Food',
	'Food' : 'Food',
	'Meal in a Pill' : 'Food',
	'Medicine' : 'Health',
	'Gaming' : 'Home',
	'House' : 'Home',
	'Kitchen' : 'Home',
	'Videophone' : 'Home',
	'Crime' : 'Issues and Events',
	'Education' : 'Issues and Events',
	'Gender Roles' : 'Issues and Events',
	'Politics' : 'Issues and Events',
	'War' : 'Issues and Events',
	'Movies' : 'Media',
	'Music' : 'Media',
	'Television' : 'Media',
	'Neil Ardley' : 'People',
	'Victor Cohn' : 'People',
	'Arthur C. Clarke' : 'People',
	'Harry Grant Dart' : 'People',
	'Walt Disney' : 'People',
	'Buckminster Fuller' : 'People',
	'Arthur Radebaugh' : 'People',
	'Frank Tinsley' : 'People',
	'John Elfreth Watkins Jr.' : 'People',
	'Automation' : 'Robotics',
	'Robots' : 'Robotics',
	'Mars' : 'Space',
	'Moon' : 'Space',
	'Space Colonies' : 'Space',
	'Space Suits' : 'Space',
	'Space Tourism' : 'Space',
	'Space Travel' : 'Space',
	'All Sports' : 'Sport',
	'Baseball' : 'Sport',
	'Football': 'Sport',
	'Golf' : 'Sport',
	'Airplanes' : 'Transportation',
	'Bicycles' : 'Transportation',
	'Cars' : 'Transportation',
	'Flying Cars' : 'Transportation',
	'Monorails' : 'Transportation',
	'Flying Machines' : 'Transportation',
	'Helicopters' : 'Transportation',
	'Hoverboards' : 'Transportation',
	'Jetpacks' : 'Transportation',
	'Moving Sidewalk' : 'Transportation',
	'Trains' : 'Transportation',
	'Weather Control' : 'Weather',
	'All World\'s Fairs' : 'World\'s Fairs',
	'New York World\'s Fairs' : 'World\'s Fairs',
	'Paris Exposition (1900)' : 'World\'s Fairs',
	'Seattle World\'s Fair (1962)' : 'World\'s Fairs'
};